"""empty message

Revision ID: f0049c4bde9e
Revises: fe0b110216b5
Create Date: 2018-08-30 15:13:50.329397

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f0049c4bde9e'
down_revision = 'fe0b110216b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('update_transaction_log', 'transaction_id')
    op.add_column('update_transaction_log', sa.Column('transaction_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('update_transaction_log', 'transaction_id')
    op.add_column('update_transaction_log', sa.Column('transaction_id', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
