"""update_transaction_log table added

Revision ID: fe0b110216b5
Revises: b121f90e85bb
Create Date: 2018-08-30 14:28:19.835390

"""
from alembic import op
import sqlalchemy as sa
import app

# revision identifiers, used by Alembic.
revision = 'fe0b110216b5'
down_revision = 'b121f90e85bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('update_transaction_log',
    sa.Column('id', app.sqlalchemy_utils.GUID(), nullable=False),
    sa.Column('item_id', app.sqlalchemy_utils.GUID(), nullable=True),
    sa.Column('attribute', sa.String(length=255), nullable=True),
    sa.Column('old_value', sa.String(length=255), nullable=True),
    sa.Column('new_value', sa.String(length=255), nullable=True),
    sa.Column('entity_type', sa.String(length=255), nullable=True),
    sa.Column('update_type', sa.String(length=255), nullable=True),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('user_id', app.sqlalchemy_utils.GUID(), nullable=True),
    sa.Column('modified_by', app.sqlalchemy_utils.GUID(), nullable=True),
    sa.Column('modified_on', sa.DateTime(), nullable=True),
    sa.Column('created_by', app.sqlalchemy_utils.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('update_transaction_log')
    # ### end Alembic commands ###
